name: DeepTransferEEG
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.4
  - pytorch::pytorch=2.0.0
  - pytorch::torchvision=0.15.0
  - pytorch::torchaudio=2.0.0
  - pytorch::pytorch-cuda=11.8
  - scipy=1.9.1
  - matplotlib=3.5.1
  - scikit-image=0.19.2
  - networkx=2.8.4
  - pywavelets=1.3.0
  - sympy=1.11.1
  - pip
  - jupyter
  - pip:
    # PyYAML wheel windows version
    # - https://raw.githubusercontent.com/Tsuasahi/python_wheels/refs/heads/main/310/PyYAML-5.4.1-cp310-cp310-win_amd64.whl
    # PyYAML wheel linux version
    - https://raw.githubusercontent.com/Tsuasahi/python_wheels/refs/heads/main/310/PyYAML-5.4.1-cp310-cp310-linux_x86_64.whl
    - moabb==0.4.6
    # moabb wheel patch for datasets download issue
    - https://raw.githubusercontent.com/Tsuasahi/python_wheels/refs/heads/main/310/moabb-0.4.6-py3-none-any.whl
    - numpy==1.24.2
    - pandas==1.4.3
    - scikit-learn==1.1.2
    - learn2learn==0.2.0
    - mne==1.1.0
    - braindecode==0.7
    - pyriemann==0.3
    - fathon==1.3.2
    - pyhht==0.1.0
    - xgboost==1.7.1
    - skorch==0.11.0
    - imbalanced-learn==0.9.1
    - torchsummary==1.5.1
    - segyio==1.9.9
    - seaborn==0.11.2
    - h5py==3.7.0
    - openpyxl==3.0.10
    - tqdm==4.64.0
    - joblib==1.1.0
    - pykalman==0.9.5
    - flopth==0.1.3
    - pooch==1.6.0
